version: '3.8'

services:
  voice-assistant:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    volumes:
      - ./models:/root/.cache/huggingface/hub